
// This file has been generated by the GUI designer. Do not modify.
namespace LampCP
{
	public partial class LampConfigWin
	{
		private global::Gtk.Table table1;
		private global::Gtk.Button btnSave;
		private global::Gtk.Label label1;
		private global::Gtk.Entry tbDocroot;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LampCP.LampConfigWin
			this.Name = "LampCP.LampConfigWin";
			this.Title = global::Mono.Unix.Catalog.GetString ("LampConfigWin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child LampCP.LampConfigWin.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnSave = new global::Gtk.Button ();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.table1.Add (this.btnSave);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnSave]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(2));
			w1.RightAttach = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Document Root");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbDocroot = new global::Gtk.Entry ();
			this.tbDocroot.CanFocus = true;
			this.tbDocroot.Name = "tbDocroot";
			this.tbDocroot.IsEditable = true;
			this.tbDocroot.InvisibleChar = '•';
			this.table1.Add (this.tbDocroot);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbDocroot]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.btnSave.Clicked += new global::System.EventHandler (this.OnBtnSaveClicked);
		}
	}
}
