
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label label3;
	private global::Gtk.Table table2;
	private global::Gtk.Button btnApacheToggle;
	private global::Gtk.Button btnConfig;
	private global::Gtk.Button btnConfigApache;
	private global::Gtk.Button btnConfigMysql;
	private global::Gtk.Button btnMysqlToggle;
	private global::Gtk.Label lblApache;
	private global::Gtk.Label lblMySql;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Lamp Comtrol Panel");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Lamp Control Panel");
		this.vbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.btnApacheToggle = new global::Gtk.Button ();
		this.btnApacheToggle.CanFocus = true;
		this.btnApacheToggle.Name = "btnApacheToggle";
		this.btnApacheToggle.UseUnderline = true;
		this.btnApacheToggle.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.table2.Add (this.btnApacheToggle);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnApacheToggle]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.btnConfig = new global::Gtk.Button ();
		this.btnConfig.CanFocus = true;
		this.btnConfig.Name = "btnConfig";
		this.btnConfig.UseUnderline = true;
		this.btnConfig.Label = global::Mono.Unix.Catalog.GetString ("Configure _LampCP");
		this.table2.Add (this.btnConfig);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnConfig]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.btnConfigApache = new global::Gtk.Button ();
		this.btnConfigApache.CanFocus = true;
		this.btnConfigApache.Name = "btnConfigApache";
		this.btnConfigApache.UseUnderline = true;
		this.btnConfigApache.Label = global::Mono.Unix.Catalog.GetString ("Configure Apache");
		this.table2.Add (this.btnConfigApache);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnConfigApache]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.btnConfigMysql = new global::Gtk.Button ();
		this.btnConfigMysql.CanFocus = true;
		this.btnConfigMysql.Name = "btnConfigMysql";
		this.btnConfigMysql.UseUnderline = true;
		this.btnConfigMysql.Label = global::Mono.Unix.Catalog.GetString ("Configure _Mysql");
		this.table2.Add (this.btnConfigMysql);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnConfigMysql]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.btnMysqlToggle = new global::Gtk.Button ();
		this.btnMysqlToggle.CanFocus = true;
		this.btnMysqlToggle.Name = "btnMysqlToggle";
		this.btnMysqlToggle.UseUnderline = true;
		this.btnMysqlToggle.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.table2.Add (this.btnMysqlToggle);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnMysqlToggle]));
		w6.LeftAttach = ((uint)(2));
		w6.RightAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.lblApache = new global::Gtk.Label ();
		this.lblApache.Name = "lblApache";
		this.lblApache.LabelProp = global::Mono.Unix.Catalog.GetString ("Apache Status");
		this.table2.Add (this.lblApache);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblApache]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.lblMySql = new global::Gtk.Label ();
		this.lblMySql.Name = "lblMySql";
		this.lblMySql.LabelProp = global::Mono.Unix.Catalog.GetString ("MySql Status");
		this.table2.Add (this.lblMySql);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblMySql]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table2]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnConfigMysql.Clicked += new global::System.EventHandler (this.OnBtnConfigMysqlClicked);
		this.btnConfigApache.Clicked += new global::System.EventHandler (this.OnBtnConfigApacheClicked);
		this.btnConfig.Clicked += new global::System.EventHandler (this.OnBtnConfigClicked);
	}
}
